jdbc:
  driver: com.mysql.jdbc.Driver
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1

spring.velocity.properties.velocimacro.library: /templates/macro.vm
spring.velocity.properties.velocimacro.library.autoreload: true

